package ru.kotov.test.task.csv.utils.exception;

public class CSVInputException extends RuntimeException {

    public CSVInputException(String message, Throwable cause) {
        super(message, cause);
    }
}
